In [1]:
cd ../

/Users/mahmoud/_code/gymlob


In [2]:
from gymlob.envs.l2_market_replay_env import L2MarketReplayEnv
from stable_baselines3 import A2C, DDPG, DQN, HER, PPO, SAC, TD3
from stable_baselines3.common.env_checker import check_env

import numpy as np
import pandas as pd
np.set_printoptions(suppress=True)

# MarketReplayEnv Gym Environment

In [3]:
SEED = 5422608

In [4]:
client_order_info = {
    "direction": "BUY",
    "quantity": 5000,
    "duration": 120,
    "benchmark": "arrival"
}

In [5]:
%%time
env = L2MarketReplayEnv(instrument='AAPL',
                        date='2014-06-28',
                        frequency='1s',
                        num_levels=10,
                        client_order_info=client_order_info,
                        orderbook_file_path='/Users/mahmoud/_code/_air/lobmod/data/INTC_2015-01-01_2015-01-31_10/INTC_2015-01-02_34200000_57600000_orderbook_10.csv',
                        orders_file_path='/Users/mahmoud/_code/_air/lobmod/data/INTC_2015-01-01_2015-01-31_10/INTC_2015-01-05_34200000_57600000_message_10.csv',
                        _seed=SEED)

CPU times: user 6.04 s, sys: 2.96 s, total: 9.01 s
Wall time: 7.5 s


In [6]:
check_env(env)

/Users/mahmoud/anaconda3/lib/python3.7/site-packages/stable_baselines3/common/env_checker.py:232: UserWarning: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) cf https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
  "We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) "


In [7]:
env.current_time

numpy.datetime64('2014-06-28T12:29:56.000000000')

In [8]:
env.observation_space

Box(-inf, inf, (4,), float64)

In [9]:
env.observation_space.sample()

array([ 53.636284  , 405.04805266,   1.14598426,  -0.56539194])

In [10]:
env.action_space

Box(0.0, 5000.0, (1,), float32)

In [11]:
env.action_space.sample()

array([3170.7761], dtype=float32)

In [12]:
env.reset()

array([ 120.        , 5000.        ,    0.01      ,   -0.76056337])

In [13]:
# test random agent

num_episodes = 2

for i in range(1, num_episodes+1):
    print(f"Episode: {i}")
    obs = env.reset()
    done = False
    step = 1
    while not done:
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        print(f"Step: {step}")
        print(f"     Observation: {obs}, Action: {action}, Reward: {reward}")
        step += 1
    print()

Episode: 1
Step: 1
     Observation: [119.         482.           0.01         0.54529136], Action: [4518.99], Reward: -22.590000000011557
Step: 2
     Observation: [118.          92.           0.01         0.59796619], Action: [390.7855], Reward: -1.9500000000009976
Step: 3
     Observation: [1.17000000e+02 4.29496344e+09 9.99999978e-03 4.77319390e-01], Action: [3944.7068], Reward: -19.72000000001009

Episode: 2
Step: 1
     Observation: [ 119.         2018.            0.01         -0.24971457], Action: [2982.7068], Reward: -21.73000000000627
Step: 2
     Observation: [118.         548.           0.01        -0.24971457], Action: [1470.3767], Reward: -7.35000000000376
Step: 3
     Observation: [ 1.17000000e+02  4.29496327e+09  9.99999978e-03 -2.49714568e-01], Action: [4570.7256], Reward: -45.550000000007174



# MarketReplayEnv Gym Environment + StableBaselines3 Agent

SEED = 5422608

client_order_info = {
    "direction": "BUY",
    "quantity": 5000,
    "duration": 120,
    "benchmark": "arrival"
}

env = L2MarketReplayEnv(instrument='AAPL',
                        date='2014-06-28',
                        frequency='1s',
                        num_levels=10,
                        client_order_info=client_order_info,
                        orderbook_file_path='/Users/mahmoud/_code/_air/lobmod/data/INTC_2015-01-01_2015-01-31_10/INTC_2015-01-02_34200000_57600000_orderbook_10.csv',
                        orders_file_path='/Users/mahmoud/_code/_air/lobmod/data/INTC_2015-01-01_2015-01-31_10/INTC_2015-01-05_34200000_57600000_message_10.csv',
                       _seed=SEED)

model = DDPG(policy='MlpPolicy', env=env, seed=SEED, verbose=1).learn(total_timesteps=100)

num_episodes = 10
       
for i in range(1, num_episodes+1):
    print(f"Episode: {i}")
    obs = env.reset()
    done = False
    step = 1
    while not done:
        action, _states = model.predict(obs)
        obs, reward, done, info = env.step(action)
        print(f"Step: {step}")
        print(f"     Observation: {obs}, Action: {action}, Reward: {reward}")
        step += 1
    print()

In [17]:
state = env.reset()

In [18]:
state

array([ 120.       , 5000.       ,    0.02     ,    0.2647059])

In [19]:
time_remaining, quantity_remaining, spread, ovi = state

In [20]:
time_remaining

120.0