In [4]:
cd ../

/Users/mahmoud/_code


In [34]:
from gymlob.envs.market_replay_env import MarketReplayEnv
from stable_baselines3 import A2C, DDPG, DQN, HER, PPO, SAC, TD3
from stable_baselines3.common.env_checker import check_env

import numpy as np
import pandas as pd
np.set_printoptions(suppress=True)

# MarketReplayEnv Gym Environment

In [6]:
SEED = 5422608

In [7]:
client_order_info = {
    "direction": "BUY",
    "quantity": 5000,
    "duration": 120,
    "benchmark": "arrival"
}

In [9]:
%%time
env = MarketReplayEnv(instrument='AAPL',
                      date='2014-06-28',
                      frequency='1s',
                      num_levels=10,
                      client_order_info=client_order_info,
                      orderbook_file_path='/Users/mahmoud/_code/_air/lobmod/data/INTC_2015-01-01_2015-01-31_10/INTC_2015-01-02_34200000_57600000_orderbook_10.csv',
                      orders_file_path='/Users/mahmoud/_code/_air/lobmod/data/INTC_2015-01-01_2015-01-31_10/INTC_2015-01-05_34200000_57600000_message_10.csv',
                      _seed=SEED)

CPU times: user 5.1 s, sys: 3 s, total: 8.1 s
Wall time: 7.59 s


In [10]:
env.current_time

Timestamp('2014-06-28 09:30:00', freq='S')

In [11]:
env.observation_space

Box(-inf, inf, (4,), float64)

In [12]:
env.observation_space.sample()

array([  41.28268349, 1177.7726619 ,    0.10452375,    0.34716735])

In [13]:
env.action_space

Box(0.0, inf, (3,), float64)

In [14]:
env.action_space.sample()

array([   0.30468637,    0.29994712, 3129.2826658 ])

In [15]:
env.reset()

array([ 120.        , 5000.        ,    0.01      ,   -0.18110237])

In [16]:
check_env(env)

/Users/mahmoud/anaconda3/lib/python3.7/site-packages/stable_baselines3/common/env_checker.py:232: UserWarning: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) cf https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
  "We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) "


In [22]:
env.orderbook_df.tail()

mid_price  spread  order_volume_imbalance  ask_price_1  \
timestamp                                                                     
2014-06-28 15:52:43     36.355    0.01               -0.863693        36.36   
2014-06-28 15:52:44     36.355    0.01               -0.868293        36.36   
2014-06-28 15:52:45     36.355    0.01               -0.860294        36.36   
2014-06-28 15:52:46     36.355    0.01               -0.859779        36.36   
2014-06-28 15:52:47     36.355    0.01               -0.821256        36.36   

                     ask_size_1  bid_price_1  bid_size_1  ask_price_2  \
timestamp                                                               
2014-06-28 15:52:43        5500        36.35       75200        36.37   
2014-06-28 15:52:44        5400        36.35       76600        36.37   
2014-06-28 15:52:45        5700        36.35       75900        36.37   
2014-06-28 15:52:46        5700        36.35       75600        36.37   
2014-06-28 15:52:47        7400        36.35       75400        36.37   

                     ask_size_2  bid_price_2  ...  bid_price_8  bid_size_8  \
timestamp                                     ...                            
2014-06-28 15:52:43       11400        36.34  ...        36.28        8800   
2014-06-28 15:52:44       11300        36.34  ...        36.28        8800   
2014-06-28 15:52:45       11300        36.34  ...        36.28        8800   
2014-06-28 15:52:46       11300        36.34  ...        36.28        8800   
2014-06-28 15:52:47       17500        36.34  ...        36.28        8800   

                     ask_price_9  ask_size_9  bid_price_9  bid_size_9  \
timestamp                                                               
2014-06-28 15:52:43        36.44       54800        36.27       13800   
2014-06-28 15:52:44        36.44       54800        36.27       13800   
2014-06-28 15:52:45        36.44       54800        36.27       13800   
2014-06-28 15:52:46        36.44       54800        36.27       13800   
2014-06-28 15:52:47        36.44       54800        36.27       13800   

                     ask_price_10  ask_size_10  bid_price_10  bid_size_10  
timestamp                                                                  
2014-06-28 15:52:43         36.45        17700         36.26         6200  
2014-06-28 15:52:44         36.45        17700         36.26         6200  
2014-06-28 15:52:45         36.45        17700         36.26         6400  
2014-06-28 15:52:46         36.45        17700         36.26         6400  
2014-06-28 15:52:47         36.45        17700         36.26         6400  

[5 rows x 43 columns]

In [35]:
allowed_timestamps = pd.date_range(start=env.timestamps[0], end=env.timestamps[-1] - np.timedelta64(120, 'm'), freq='1s')

In [36]:
allowed_timestamps

DatetimeIndex(['2014-06-28 09:30:00', '2014-06-28 09:30:01',
               '2014-06-28 09:30:02', '2014-06-28 09:30:03',
               '2014-06-28 09:30:04', '2014-06-28 09:30:05',
               '2014-06-28 09:30:06', '2014-06-28 09:30:07',
               '2014-06-28 09:30:08', '2014-06-28 09:30:09',
               ...
               '2014-06-28 13:52:38', '2014-06-28 13:52:39',
               '2014-06-28 13:52:40', '2014-06-28 13:52:41',
               '2014-06-28 13:52:42', '2014-06-28 13:52:43',
               '2014-06-28 13:52:44', '2014-06-28 13:52:45',
               '2014-06-28 13:52:46', '2014-06-28 13:52:47'],
              dtype='datetime64[ns]', length=15768, freq='S')

In [33]:
env.timestamps[-1]

Timestamp('2014-06-28 15:52:47', freq='S')

In [31]:
start_time

Timestamp('2014-06-28 09:30:00', freq='S')

In [32]:
end_time

Timestamp('2014-06-28 17:52:47', freq='S')

In [20]:
env.orderbook_df.loc[np.datetime64('2015-01-02T15:52:48.000000000')]

KeyError: numpy.datetime64('2015-01-02T15:52:48.000000000')

# MarketReplayEnv Gym Environment + StableBaselines3 Agent

In [3]:
SEED = 5422608

client_order_info = {
    "direction": "BUY",
    "quantity": 5000,
    "duration": 120,
    "benchmark": "arrival"
}

env = MarketReplayEnv(instrument='AAPL',
                      date='2014-06-28',
                      frequency='1s',
                      num_levels=10,
                      client_order_info=client_order_info,
                      orderbook_file_path='/Users/mahmoud/_code/_air/lobmod/data/INTC_2015-01-01_2015-01-31_10/INTC_2015-01-02_34200000_57600000_orderbook_10.csv',
                      orders_file_path='/Users/mahmoud/_code/_air/lobmod/data/INTC_2015-01-01_2015-01-31_10/INTC_2015-01-05_34200000_57600000_message_10.csv',
                      _seed=SEED)

model = DDPG(policy='MlpPolicy', env=env, seed=SEED, verbose=1).learn(total_timesteps=100)

num_episodes = 10

obs = env.reset()
for i in range(num_episodes):

    action, _states = model.predict(obs)
    obs, reward, done, info = env.step(action)

    if done:
        obs = env.reset()   

Using cpu device
Wrapping the env in a DummyVecEnv.
----------------------------
| time/              |     |
|    episodes        | 4   |
|    fps             | 477 |
|    time_elapsed    | 0   |
|    total timesteps | 11  |
----------------------------
----------------------------
| time/              |     |
|    episodes        | 8   |
|    fps             | 530 |
|    time_elapsed    | 0   |
|    total timesteps | 22  |
----------------------------
----------------------------
| time/              |     |
|    episodes        | 12  |
|    fps             | 571 |
|    time_elapsed    | 0   |
|    total timesteps | 36  |
----------------------------
----------------------------
| time/              |     |
|    episodes        | 16  |
|    fps             | 588 |
|    time_elapsed    | 0   |
|    total timesteps | 47  |
----------------------------
----------------------------
| time/              |     |
|    episodes        | 20  |
|    fps             | 603 |
|    time_elapsed   

/Users/mahmoud/anaconda3/lib/python3.7/site-packages/stable_baselines3/common/policies.py:326: RuntimeWarning: invalid value encountered in multiply
  return low + (0.5 * (scaled_action + 1.0) * (high - low))
